//
//  SettingsPresenter.swift
//  InstaZoom
//
//  Created Anıl Taskıran on 7.10.2019.
//  Copyright © 2019 Anıl  Taskıran. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import StoreKit

//MARK: - FavoritePresenterInterface
protocol SettingsPresenterInterface: class {
    func load()
    func viewDidLoad()
    func rateStackViewTapped()
    func feedbackStackViewTapped()
    func clearHistoryStackViewTapped()
    func balllabAppStackViewTapped()
    func bitcoinAppStackViewTapped()
}

class SettingsPresenter {
    weak private var view: SettingsViewInterface?
    private let router: SettingsRouterInterface

    init(view: SettingsViewInterface, router: SettingsRouterInterface) {
        self.view = view
        self.router = router
    }

    func setBuildVersion() {
        guard let dictionary = Bundle.main.infoDictionary,
            let version = dictionary["CFBundleShortVersionString"] as? String,
            let build = dictionary["CFBundleVersion"] as? String else {
            return
        }

        view?.setBuildVersion(text: "\(version) (\(build))")
    }
}

extension SettingsPresenter: SettingsPresenterInterface {
    func balllabAppStackViewTapped() {
        if let url = URL(string: "https://apps.apple.com/us/app/balllab/id1473003145") {
            UIApplication.shared.open(url)
        }
    }

    func bitcoinAppStackViewTapped() {
        if let url = URL(string: "https://google.com") {
            UIApplication.shared.open(url)
        }
    }

    func load() {
        view?.setTitle(Localizable.Settings.title.localized)
    }

    func viewDidLoad() {
        view?.setScordsViewToTitleView()
        view?.clearNavigationBarBackground()
        view?.setLocalizedTexts()
        view?.addTapGestures()
        setBuildVersion()
    }

    func rateStackViewTapped() {
//        StoreReviewManager.shared.goToAppStore()
    }

    func feedbackStackViewTapped() {
        let recipients = ["scordsApp@gmail.com"]
        let subject = "Feedback For App"
        let body = "Hello!"
        router.showMailComposeViewController(recipients: recipients, subject: subject, body: body)
    }

    func clearHistoryStackViewTapped() {
        router.showClearHistoryAlertController(didTapped: { [weak self] in
            if IAPHelper.shared.userType == .pro {
                CoreDataManager().removeAllHistory()
            } else {
                let alertView = UIAlertController(title: "PicHunter", message: "You need to be pro for removing search history", preferredStyle: .alert)

                alertView.addAction(.init(title: "Okay", style: .destructive, handler: { [weak self] (_) in

                    self?.router.navigationController?.showIAPView()

                }))

                self?.router.navigationController?.present(alertView, animated: true)
            }
        })
    }
}

